# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accueil_CF.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_CF(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 499)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon_only_widget = QtWidgets.QWidget(Form)
        self.icon_only_widget.setGeometry(QtCore.QRect(9, 9, 38, 481))
        self.icon_only_widget.setMaximumSize(QtCore.QSize(60, 16777215))
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(73, 144, 196);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    height: 30px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color: #1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Accueil_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.Accueil_1.setStyleSheet("QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color: #1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.Accueil_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../EduOps-BackOffice-dev-main/images/page-accueil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Accueil_1.setIcon(icon)
        self.Accueil_1.setCheckable(True)
        self.Accueil_1.setAutoExclusive(True)
        self.Accueil_1.setObjectName("Accueil_1")
        self.verticalLayout_2.addWidget(self.Accueil_1)
        self.ExploiterEnseigne_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.ExploiterEnseigne_1.setStyleSheet("text-align:center;")
        self.ExploiterEnseigne_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../EduOps-BackOffice-dev-main/images/cahier-de-texte.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExploiterEnseigne_1.setIcon(icon1)
        self.ExploiterEnseigne_1.setCheckable(True)
        self.ExploiterEnseigne_1.setAutoExclusive(True)
        self.ExploiterEnseigne_1.setObjectName("ExploiterEnseigne_1")
        self.verticalLayout_2.addWidget(self.ExploiterEnseigne_1)
        self.ExploiterPV_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.ExploiterPV_1.setStyleSheet("text-align:center;\n"
"")
        self.ExploiterPV_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../EduOps-BackOffice-dev-main/images/enseignement.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExploiterPV_1.setIcon(icon2)
        self.ExploiterPV_1.setCheckable(True)
        self.ExploiterPV_1.setAutoExclusive(True)
        self.ExploiterPV_1.setObjectName("ExploiterPV_1")
        self.verticalLayout_2.addWidget(self.ExploiterPV_1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(38, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_9 = QtWidgets.QPushButton(self.icon_only_widget)
        self.pushButton_9.setStyleSheet("text-align:center;\n"
"")
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../SGBD_PROJET/Images/sortir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.icon_name_widget = QtWidgets.QWidget(Form)
        self.icon_name_widget.setGeometry(QtCore.QRect(53, 9, 187, 481))
        self.icon_name_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(73, 144, 196);\n"
"}\n"
"\n"
"QPushButton{\n"
"    text-align:left;\n"
"    color: white;\n"
"    height: 30px;\n"
"    border:none;\n"
"    font-family: \"Comic Sans MS\", cursive, sans-serif; \n"
"    font-size: 12px; \n"
"    padding-left:10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color: #1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_2.setStyleSheet("image: url(:/logo pers.jpeg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Accueil_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.Accueil_2.setIcon(icon)
        self.Accueil_2.setCheckable(True)
        self.Accueil_2.setAutoExclusive(True)
        self.Accueil_2.setObjectName("Accueil_2")
        self.verticalLayout.addWidget(self.Accueil_2)
        self.ExploiterEnseigne_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.ExploiterEnseigne_2.setIcon(icon1)
        self.ExploiterEnseigne_2.setCheckable(True)
        self.ExploiterEnseigne_2.setAutoExclusive(True)
        self.ExploiterEnseigne_2.setObjectName("ExploiterEnseigne_2")
        self.verticalLayout.addWidget(self.ExploiterEnseigne_2)
        self.ExploiterPV_2 = QtWidgets.QPushButton(self.icon_name_widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../SGBD_PROJET/Images/enseignement.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExploiterPV_2.setIcon(icon4)
        self.ExploiterPV_2.setCheckable(True)
        self.ExploiterPV_2.setAutoExclusive(True)
        self.ExploiterPV_2.setObjectName("ExploiterPV_2")
        self.verticalLayout.addWidget(self.ExploiterPV_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(18, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.pushButton_25 = QtWidgets.QPushButton(self.icon_name_widget)
        self.pushButton_25.setIcon(icon3)
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_4.addWidget(self.pushButton_25)
        self.main_menu = QtWidgets.QWidget(Form)
        self.main_menu.setGeometry(QtCore.QRect(246, 9, 572, 481))
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header = QtWidgets.QWidget(self.main_menu)
        self.header.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.header.setObjectName("header")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu = QtWidgets.QPushButton(self.header)
        self.menu.setStyleSheet("border: none;\n"
"")
        self.menu.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../EduOps-BackOffice-dev-main/images/barre-de-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon5)
        self.menu.setIconSize(QtCore.QSize(30, 30))
        self.menu.setCheckable(True)
        self.menu.setObjectName("menu")
        self.horizontalLayout_5.addWidget(self.menu)
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.header)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_29 = QtWidgets.QPushButton(self.header)
        self.pushButton_29.setStyleSheet("    border:none;\n"
"\n"
"")
        self.pushButton_29.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_29.setIcon(icon6)
        self.pushButton_29.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_4.addWidget(self.pushButton_29)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_30 = QtWidgets.QPushButton(self.header)
        self.pushButton_30.setStyleSheet("border: none;\n"
"\n"
"")
        self.pushButton_30.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../EduOps-BackOffice-dev-main/images/profil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_30.setIcon(icon7)
        self.pushButton_30.setIconSize(QtCore.QSize(30, 20))
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_5.addWidget(self.pushButton_30)
        self.verticalLayout_5.addWidget(self.header)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_menu)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Accueil = QtWidgets.QWidget()
        self.Accueil.setObjectName("Accueil")
        self.label_4 = QtWidgets.QLabel(self.Accueil)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 361, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.Accueil)
        self.ExploiterRapport = QtWidgets.QWidget()
        self.ExploiterRapport.setObjectName("ExploiterRapport")
        self.widget = QtWidgets.QWidget(self.ExploiterRapport)
        self.widget.setGeometry(QtCore.QRect(10, -30, 511, 411))
        self.widget.setObjectName("widget")
        self.button = QtWidgets.QPushButton(self.widget)
        self.button.setGeometry(QtCore.QRect(20, 90, 351, 20))
        self.button.setStyleSheet("background-color: rgb(73, 144, 196);\n"
"\n"
"")
        self.button.setObjectName("button")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(30, 110, 241, 261))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableau = QtWidgets.QTableWidget(self.groupBox)
        self.tableau.setObjectName("tableau")
        self.tableau.setColumnCount(3)
        self.tableau.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableau.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableau.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableau.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableau, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    border: none;\n"
"    margin: 0;\n"
"    border-bottom: 1px solid black; /* Couleur de la ligne */\n"
"}")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.stackedWidget.addWidget(self.ExploiterRapport)
        self.ExploiterEnseigne = QtWidgets.QWidget()
        self.ExploiterEnseigne.setObjectName("ExploiterEnseigne")
        self.widget_2 = QtWidgets.QWidget(self.ExploiterEnseigne)
        self.widget_2.setGeometry(QtCore.QRect(19, 9, 521, 421))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 451, 391))
        self.widget_3.setObjectName("widget_3")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(40, 40, 37, 12))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 110, 241, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 80, 221, 21))
        self.pushButton_2.setStyleSheet("background-color: rgb(73, 144, 196);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 40, 21, 16))
        self.label.setObjectName("label")
        self.DateEdit_2 = QtWidgets.QDateEdit(self.widget_3)
        self.DateEdit_2.setGeometry(QtCore.QRect(40, 20, 221, 31))
        self.DateEdit_2.setStyleSheet("QDateEdit {\n"
"    border: none;\n"
"    margin: 0;\n"
"    border-bottom: 1px solid black; /* Couleur de la ligne */\n"
"}")
        self.DateEdit_2.setObjectName("DateEdit_2")
        self.stackedWidget.addWidget(self.ExploiterEnseigne)
        self.ExploiterPV = QtWidgets.QWidget()
        self.ExploiterPV.setObjectName("ExploiterPV")
        self.widget_4 = QtWidgets.QWidget(self.ExploiterPV)
        self.widget_4.setGeometry(QtCore.QRect(10, 0, 531, 351))
        self.widget_4.setObjectName("widget_4")
        self.stackedWidget.addWidget(self.ExploiterPV)
        self.verticalLayout_5.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.menu.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.menu.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.pushButton_9.toggled['bool'].connect(Form.close) # type: ignore
        self.pushButton_25.toggled['bool'].connect(Form.close) # type: ignore
        self.Accueil_1.toggled['bool'].connect(self.Accueil_2.setChecked) # type: ignore
        self.Accueil_2.toggled['bool'].connect(self.Accueil_1.setChecked) # type: ignore
        self.ExploiterEnseigne_1.toggled['bool'].connect(self.ExploiterEnseigne_2.setChecked) # type: ignore
        self.ExploiterEnseigne_2.toggled['bool'].connect(self.ExploiterEnseigne_1.setChecked) # type: ignore
        self.ExploiterPV_1.toggled['bool'].connect(self.ExploiterPV_2.setChecked) # type: ignore
        self.ExploiterPV_2.toggled['bool'].connect(self.ExploiterPV_1.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Chef de departement"))
        self.Accueil_2.setText(_translate("Form", "Accueil"))
        self.ExploiterEnseigne_2.setText(_translate("Form", "Situation enseignement"))
        self.ExploiterPV_2.setText(_translate("Form", "Transmettre PV"))
        self.pushButton_25.setText(_translate("Form", "Deconnexion"))
        self.label_4.setText(_translate("Form", "Bienvenue dans la page d accueil"))
        self.button.setText(_translate("Form", "Valider"))
        self.groupBox.setTitle(_translate("Form", "Rapport"))
        item = self.tableau.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nom Rapport"))
        item = self.tableau.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Date Rapport"))
        item = self.tableau.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Contenu"))
        self.label_7.setText(_translate("Form", " la date "))
        self.groupBox_2.setTitle(_translate("Form", "PV"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nom Enseignant"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "contenu"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date PV"))
        self.pushButton_2.setText(_translate("Form", "Valider"))
        self.label.setText(_translate("Form", "DATE"))
