# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys


class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(890, 733)
        Test.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Test)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalFrame_2 = QtWidgets.QFrame(parent=Test)
        self.verticalFrame_2.setGeometry(QtCore.QRect(180, 0, 2481, 81))
        self.verticalFrame_2.setStyleSheet("background-color: rgb(73, 144, 196)")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=Test)
        self.label_3.setGeometry(QtCore.QRect(170, 130, 601, 71))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=Test)
        self.lineEdit.setGeometry(QtCore.QRect(300, 280, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 20px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Test)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 400, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 20px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=Test)
        self.pushButton.setGeometry(QtCore.QRect(240, 560, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(75, 56, 56);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=Test)
        self.label.setGeometry(QtCore.QRect(210, 280, 61, 61))
        self.label.setStyleSheet("image:url(:/res/loco pers.jpeg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=Test)
        self.widget.setGeometry(QtCore.QRect(0, 0, 181, 81))
        self.widget.setStyleSheet("image: url(:/res/logo esp.jpeg);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=Test)
        self.widget_2.setGeometry(QtCore.QRect(180, 400, 121, 61))
        self.widget_2.setStyleSheet("image: url(:/res/mdp.png);")
        self.widget_2.setObjectName("widget_2")
        self.verticalFrame_3 = QtWidgets.QFrame(parent=Test)
        self.verticalFrame_3.setGeometry(QtCore.QRect(-10, 660, 2561, 80))
        self.verticalFrame_3.setStyleSheet("background-color: rgb(73, 144, 196)")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "Test"))
        self.label_3.setText(_translate("Test", "     BIENVENUE DANS VOTRE PLATEFORME"))
        self.lineEdit.setText(_translate("Test", "    Login"))
        self.lineEdit_2.setText(_translate("Test", "   Mot de passe"))
        self.pushButton.setToolTip(_translate("Test", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton.setText(_translate("Test", "CONNEXION"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Test()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())

